Update readme.md
salahawk/bittensor-model-finetune pull request #3
Opened 2023-06-20 18:59 UTC by asifehmad

The cloning link of the repository was directed to some other repository.

2023-06-20 21:42 UTC, salahawk requested changes

2023-06-20 21:42 UTC, salahawk commented on gpt4all/readme.md
> +git clone https://github.com/salahawk/bittensor-model-finetune/gpt4all
should be `https://github.com/salahawk/bittensor-model-finetune`?
don't need `gpt4all` appended?

2023-06-21 12:13 UTC, asifehmad reviewed
Yes, you are right it should be that way.

2023-06-21 12:43 UTC, salahawk commented
@asifehmad can you plz fix this, so that we can merge this PR?

2023-06-21 12:52 UTC, salahawk approved these changes
Looks good, thanks

2023-06-21 12:52 UTC, merged